// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDunJtwC-sqmWOYKM-M988fmquRDgOJQlg',
    appId: '1:248513561291:web:1c2b959211aad00e1a114e',
    messagingSenderId: '248513561291',
    projectId: 'currency-6731f',
    authDomain: 'currency-6731f.firebaseapp.com',
    storageBucket: 'currency-6731f.firebasestorage.app',
    measurementId: 'G-K62472N2ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACARfD-QeIagwz6poyl1GhBZb2QZLjBpU',
    appId: '1:248513561291:android:5c7d0af89524ca371a114e',
    messagingSenderId: '248513561291',
    projectId: 'currency-6731f',
    storageBucket: 'currency-6731f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxXJJvbKr_egJBcIle17MwgJuZOE4kTww',
    appId: '1:248513561291:ios:87ba103aa18bc8ed1a114e',
    messagingSenderId: '248513561291',
    projectId: 'currency-6731f',
    storageBucket: 'currency-6731f.firebasestorage.app',
    iosBundleId: 'com.example.thoughtBox',
  );
}
